name: Execute OSCAL Assessment Workflow
description: Executes assessment workflow with an OSCAL YAML Assessment Plan and generate an OSCAL YAML Assessment Result
inputs:
  assessment_plan_path:
    description: Path to the OSCAL Assessment Plan YAML file exists
    required: true
  assessment_results_path:
    description: Path to the OSCAL Assessment Results YAML file be generated
    required: true
runs:
  using: composite
  steps:
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: |
        INPUT_ASSESSMENT_PLAN_PATH=${INPUT_ASSESSMENT_PLAN_PATH} \
        INPUT_ASSESSMENT_RESULTS_PATH=${INPUT_ASSESSMENT_RESULTS_PATH} \
          $GITHUB_ACTION_PATH/assess.py
      shell: bash
